language: php

matrix:
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: 8.0
  allow_failures:
    - php: nightly

before_script :
  - hostname
  - composer update

after_script:
  - CODECLIMATE_REPO_TOKEN="f7ac76691ae172e8bc7d110a38188016f816d365e1c41a092b5bd54890001574" vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"

script: 
  - ./vendor/bin/phpcs --warning-severity=6 --standard=PSR2 src tests
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-text

notifications:
  email:
    - matthew@baggett.me
